### ISSUE TITLE
redux toolkit

### ISSUE THREAD

**Issue by ExploreBaduk** [bezkoder/redux-refresh-token-axios#1]

**Comment by ExploreBaduk** [comment]
I think I managed to make it work by having 

**export const refreshToken = createAsyncThunk(
  "auth/refreshtoken",
  async (accessToken) => {
    return accessToken;
  }
);**

and also having this 

**[refreshToken.fulfilled]: (state, action) => {
      state.isLoggedIn = true;
      state.user = { ...user, accessToken: action.payload };
    },**
Is there something wrong here, or should I just leave it like this?

**Comment by Quernest** [comment]
> I think I managed to make it work by having
> 
> **export const refreshToken = createAsyncThunk( "auth/refreshtoken", async (accessToken) => { return accessToken; } );**
> 
> and also having this
> 
> **[refreshToken.fulfilled]: (state, action) => { state.isLoggedIn = true; state.user = { ...user, accessToken: action.payload }; },** Is there something wrong here, or should I just leave it like this?

Hi @ExploreBaduk 

First of all `refreshToken` must be performed using a `refresh` token (not `access`).

in your `authSlice.js`
```ts
export const refreshToken = createAsyncThunk(
  'auth/refreshtoken',
  async (token) => {
    const response = await api.auth.refresh(token);
    return response.data;
  },
);
```

then add new case in extra reducer

```ts
[refreshToken.fulfilled]: (state, { payload }) => {
  // payload contains new pair `accessToken` and `refreshToken`
  // save them where u want
  state.accessToken = payload.accessToken;
  state.refreshToken = payload.refreshToken;
},
```
it's better to use selector
```ts
export const isLoggedIn = state => !!state.auth.accessToken;
```
